#!/bin/bash
 
#Diretivas PBS. Especificam recursos que serao utilizados pelo job 
 
#PBS -N Bora 
#PBS -l nodes=1:ppn=23,mem=20gb,walltime=72:00:00
#PBS -q qtime
#PBS -m ae
#mensagem sera enviada: a – abort; b – begin; e – end 
#PBS -M eduardo.menezes@ufv.br 
 
cd $PBS_O_WORKDIR 
 
#Habilita o carregamento de modulos
source /etc/profile.d/modules.sh 
 
#Carrega os modulos
module load freebayes/1.3.1 

#Os comandos a serem executados. O seu roteiro propriamente dito.
#Comandos a partir daqui

#jp14
freebayes -f Ref_R64.fasta markdup_JP14.bam > var_JP14.vcf

#ip9
freebayes -f Ref_R64.fasta markdup_IP9.bam > var_IP9.vcf


#Fim do Script
