#!/bin/bash
 
#Diretivas PBS. Especificam recursos que serao utilizados pelo job 
 
#PBS -N Bora 
#PBS -l nodes=1:ppn=23,mem=20gb,walltime=72:00:00
#PBS -q qtime
#PBS -m ae
#mensagem sera enviada: a – abort; b – begin; e – end 
#PBS -M eduardo.menezes@ufv.br 
 
cd $PBS_O_WORKDIR 
 
#Habilita o carregamento de modulos
source /etc/profile.d/modules.sh 
 
#Carrega os modulos
module load java/jdk11.0.7 

#Os comandos a serem executados. O seu roteiro propriamente dito.
#Comandos a partir daqui

#ip9
java -Xmx8g -jar snpEff/snpEff.jar -v R64-1-1.105 filtered_var_IP9.vcf > filtered_var_IP9.ann.vcf

#Fim do Script
