#!/bin/bash
 
#Diretivas PBS. Especificam recursos que serao utilizados pelo job 
 
#PBS -N Bora 
#PBS -l nodes=1:ppn=23,mem=20gb,walltime=72:00:00
#PBS -q qtime
#PBS -m ae
#mensagem sera enviada: a – abort; b – begin; e – end 
#PBS -M eduardo.menezes@ufv.br 
 
cd $PBS_O_WORKDIR 
 
#Habilita o carregamento de modulos
source /etc/profile.d/modules.sh 
 
#Carrega os modulos
module load vcftools/0.1.16 

#Os comandos a serem executados. O seu roteiro propriamente dito.
#Comandos a partir daqui

QUAL=30
MIN_DEPTH=20
MAX_DEPTH=300

VCF_IN=var_JP14.vcf.gz
VCF_OUT=filtered_var_JP14.vcf.gz
vcftools --gzvcf $VCF_IN \
--minQ $QUAL \
--min-meanDP $MIN_DEPTH --max-meanDP $MAX_DEPTH \
--minDP $MIN_DEPTH --maxDP $MAX_DEPTH --recode --stdout | gzip -c > \
$VCF_OUT


#Fim do Script
