#!/bin/bash
 
#Diretivas PBS. Especificam recursos que serao utilizados pelo job 
 
#PBS -N Busco 
#PBS -l nodes=1:ppn=2,mem=8gb,walltime=72:00:00
#PBS -q qtime
#PBS -m ae
#mensagem sera enviada: a – abort; b – begin; e – end 
#PBS -M eduardo.menezes@ufv.br 
 
cd $PBS_O_WORKDIR 
 
#Habilita o carregamento de modulos
source /etc/profile.d/modules.sh 
 
#Carrega os modulos
module load python/3.7.4
module load r/4.2.1 
module load busco/5.0.0

#Os comandos a serem executados. O seu roteiro propriamente dito.
#Comandos a partir daqui

python3 generate_plot.py -wd BUSCO_summaries

#Fim do Script
